# Generated by Django 5.2.1 on 2025-05-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='nom',
            field=models.CharField(choices=[('Paris', 'Paris'), ('Marseille', 'Marseille'), ('Lyon', 'Lyon'), ('Toulouse', 'Toulouse'), ('Nice', 'Nice'), ('Nantes', 'Nantes'), ('Strasbourg', 'Strasbourg'), ('Montpellier', 'Montpellier'), ('Bordeaux', 'Bordeaux'), ('Lille', 'Lille'), ('Rennes', 'Rennes'), ('Reims', 'Reims'), ('Le Havre', 'Le Havre'), ('Saint-Étienne', 'Saint-Étienne'), ('Toulon', 'Toulon')], max_length=100, unique=True),
        ),
    ]
